[package]
name = "example"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
bprust-sys = { version = "0.1.0", path = "../bprust-sys" }

[build-dependencies]
bprust-build = { path = "../bprust-build" }
